repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.2.1"
    hooks:
      - id: prettier
        exclude: '^.*\.(html|min\.js)$'
  - repo: https://github.com/psf/black
    rev: "19.10b0"
    hooks:
      - id: black
        additional_dependencies: ["click<8.0"]
