#!/usr/bin/env python
# -*- coding: utf-8 -*-

# CAVEAT UTILITOR
#
# This file was automatically generated by Grako.
#
#    https://pypi.python.org/pypi/grako/
#
# Any changes you make to it will be overwritten the next time
# the file is generated.


from __future__ import print_function, division, absolute_import, unicode_literals

from grako.parsing import graken, Parser
from grako.util import re, RE_FLAGS  # noqa


__version__ = (2016, 2, 3, 20, 13, 21, 2)

__all__ = [
    'depfileParser',
    'depfileSemantics',
    'main'
]


class depfileParser(Parser):
    def __init__(self,
                 whitespace=None,
                 nameguard=None,
                 comments_re=None,
                 eol_comments_re=None,
                 ignorecase=None,
                 left_recursion=True,
                 **kwargs):
        super(depfileParser, self).__init__(
            whitespace=whitespace,
            nameguard=nameguard,
            comments_re=comments_re,
            eol_comments_re=eol_comments_re,
            ignorecase=ignorecase,
            left_recursion=left_recursion,
            **kwargs
        )

    @graken()
    def _ws_(self):
        self._pattern(r'\s*')

    @graken()
    def _triple_quoted_string_(self):
        self._pattern(r'"""(?:[^"]|"{1,2}(?!"))+"""')

    @graken()
    def _single_quoted_string_(self):
        self._pattern(r'"[^"]*"')

    @graken()
    def _quoted_string_(self):
        with self._choice():
            with self._option():
                self._triple_quoted_string_()
            with self._option():
                self._single_quoted_string_()
            self._error('no available options')

    @graken()
    def _identifier_(self):
        self._pattern(r'[A-Za-z_]+[A-Za-z0-9_-]*')

    @graken()
    def _json_name_value_pair_(self):
        self._quoted_string_()
        self._ws_()
        self._token(':')
        self._ws_()
        self._quoted_string_()

    @graken()
    def _json_obj_(self):
        self._token('{')
        self._ws_()
        self._json_name_value_pair_()
        self._ws_()

        def block0():
            self._token(',')
            self._ws_()
            self._json_name_value_pair_()
            self._ws_()
        self._closure(block0)
        self._token('}')

    @graken()
    def _input_specs_(self):
        self._identifier_()
        self._ws_()
        self._token('=')
        self._ws_()
        self._json_obj_()

        def block0():
            self._ws_()
            self._token(',')
            self._ws_()
            self._identifier_()
            self._token('=')
            self._ws_()
            self._json_obj_()
        self._closure(block0)

    @graken()
    def _output_specs_(self):
        self._identifier_()
        self._ws_()
        self._token('=')
        self._ws_()
        self._quoted_string_()

        def block0():
            self._ws_()
            self._token(',')
            self._ws_()
            self._identifier_()
            self._ws_()
            self._token('=')
            self._ws_()
            self._quoted_string_()
        self._closure(block0)

    @graken()
    def _statement_(self):
        with self._group():
            with self._choice():
                with self._option():
                    self._token('inputs')
                    self._ws_()
                    self._token(':')
                    self._ws_()
                    self._input_specs_()
                with self._option():
                    self._token('outputs')
                    self._ws_()
                    self._token(':')
                    self._ws_()
                    self._output_specs_()
                with self._option():
                    self._token('script')
                    self._ws_()
                    self._token(':')
                    self._ws_()
                    self._quoted_string_()
                with self._option():
                    self._token('options')
                    self._ws_()
                    self._token(':')
                    self._ws_()
                    self._identifier_()

                    def block0():
                        self._ws_()
                        self._token(',')
                        self._ws_()
                        self._identifier_()
                    self._closure(block0)
                self._error('no available options')
        self._ws_()

    @graken()
    def _statements_(self):

        def block0():
            self._statement_()
        self._positive_closure(block0)

    @graken()
    def _rule_(self):
        self._ws_()
        self._token('rule')
        self._ws_()
        self._identifier_()
        self._ws_()
        self._token(':')
        self._ws_()
        self._statements_()
        self._ws_()

    @graken()
    def _rules_(self):

        def block0():
            self._rule_()
        self._positive_closure(block0)

        self._check_eof()


class depfileSemantics(object):
    def ws(self, ast):
        return ast

    def triple_quoted_string(self, ast):
        return ast

    def single_quoted_string(self, ast):
        return ast

    def quoted_string(self, ast):
        return ast

    def identifier(self, ast):
        return ast

    def json_name_value_pair(self, ast):
        return ast

    def json_obj(self, ast):
        return ast

    def input_specs(self, ast):
        return ast

    def output_specs(self, ast):
        return ast

    def statement(self, ast):
        return ast

    def statements(self, ast):
        return ast

    def rule(self, ast):
        return ast

    def rules(self, ast):
        return ast


def main(filename, startrule, trace=False, whitespace=None, nameguard=None):
    import json
    with open(filename) as f:
        text = f.read()
    parser = depfileParser(parseinfo=False)
    ast = parser.parse(
        text,
        startrule,
        filename=filename,
        trace=trace,
        whitespace=whitespace,
        nameguard=nameguard)
    print('AST:')
    print(ast)
    print()
    print('JSON:')
    print(json.dumps(ast, indent=2))
    print()

if __name__ == '__main__':
    import argparse
    import string
    import sys

    class ListRules(argparse.Action):
        def __call__(self, parser, namespace, values, option_string):
            print('Rules:')
            for r in depfileParser.rule_list():
                print(r)
            print()
            sys.exit(0)

    parser = argparse.ArgumentParser(description="Simple parser for depfile.")
    parser.add_argument('-l', '--list', action=ListRules, nargs=0,
                        help="list all rules and exit")
    parser.add_argument('-n', '--no-nameguard', action='store_true',
                        dest='no_nameguard',
                        help="disable the 'nameguard' feature")
    parser.add_argument('-t', '--trace', action='store_true',
                        help="output trace information")
    parser.add_argument('-w', '--whitespace', type=str, default=string.whitespace,
                        help="whitespace specification")
    parser.add_argument('file', metavar="FILE", help="the input file to parse")
    parser.add_argument('startrule', metavar="STARTRULE",
                        help="the start rule for parsing")
    args = parser.parse_args()

    main(
        args.file,
        args.startrule,
        trace=args.trace,
        whitespace=args.whitespace,
        nameguard=not args.no_nameguard
    )
