#!/usr/bin/env python3
# copyright: ignore
#
# CAVEAT UTILITOR
#
#  This file was automatically generated by 竜TatSu v5.18.0
#
#     https://pypi.python.org/pypi/tatsu/
#
#  Any changes you make to it will be overwritten the next time
#  the file is generated.
#
# noqa # type: ignore # ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Any

from tatsu import decorators as tatsu
from tatsu.contexts import Ctx
from tatsu.parserconfig import ParserConfig
from tatsu.parsing import Parser, generic_main
from tatsu.tokenizing.buffer import Buffer
from tatsu.tokenizing.textlines import TextLinesTokenizer


KEYWORDS: set[str] = set()


class depfileTokenizer(TextLinesTokenizer):
    def __init__(
        self,
        text, /,
        config: ParserConfig | None = None,
        **settings,
    ) -> None:
        config = ParserConfig.new(
            config=config,
            whitespace=None,
            nameguard=None,
            ignorecase=False,
            namechars='',
            parseinfo=False,
            comments=r'None',
            eol_comments=r'(?m)#.*?$',
            keywords=KEYWORDS,
            start='triple_dbl_quoted_string',
        )
        assert isinstance(config, ParserConfig)
        config = config.override(**settings)

        super().__init__(text, config=config)


class depfileBuffer(Buffer):  # NOTE: backwards compatibility
    def __init__(
        self,
        text, /,
        config: ParserConfig | None = None,
        **settings,
    ) -> None:
        config = ParserConfig.new(
            config=config,
            whitespace=None,
            nameguard=None,
            ignorecase=False,
            namechars='',
            parseinfo=False,
            comments=r'None',
            eol_comments=r'(?m)#.*?$',
            keywords=KEYWORDS,
            start='triple_dbl_quoted_string',
        )
        assert isinstance(config, ParserConfig)
        config = config.override(**settings)

        super().__init__(text, config=config)


class depfileParser(Parser):
    def __init__(self, /, config: ParserConfig | None = None, **settings):
        config = ParserConfig.new(config, **settings)
        rulessource = depfileRules()
        assert isinstance(config, ParserConfig)
        tokenizercls = config.tokenizercls or depfileTokenizer

        super().__init__(rulessource, config=config, tokenizercls=tokenizercls)


class depfileRules:
    def __init__(self, /, config: ParserConfig | None = None, **settings):
        config = ParserConfig.new(
            config=config,
            whitespace=None,
            nameguard=None,
            ignorecase=False,
            namechars='',
            parseinfo=False,
            comments=r'None',
            eol_comments=r'(?m)#.*?$',
            keywords=KEYWORDS,
            start='triple_dbl_quoted_string',
        )
        assert isinstance(config, ParserConfig)
        config = config.override(**settings)
        self._config = config


    @tatsu.rule
    def triple_dbl_quoted_string(self, ctx: Ctx) -> Any:
        ctx.pattern(r'"""(?:[^"]|"{1,2}(?!"))+"""')

    @tatsu.rule
    def dbl_quoted_string(self, ctx: Ctx) -> Any:
        ctx.pattern(r'"[^"]*"')

    @tatsu.rule
    def triple_squoted_string(self, ctx: Ctx) -> Any:
        ctx.pattern(r"'''(?:[^']|'{1,2}(?!'))+'''")

    @tatsu.rule
    def squoted_string(self, ctx: Ctx) -> Any:
        ctx.pattern(r"'[^']*'")

    @tatsu.rule
    def quoted_string(self, ctx: Ctx) -> Any:
        with ctx.choice() as α:
            @α.option
            def _(ctx: Ctx) -> Any:
                self.triple_dbl_quoted_string(ctx)
            @α.option
            def _(ctx: Ctx) -> Any:
                self.dbl_quoted_string(ctx)
            @α.option
            def _(ctx: Ctx) -> Any:
                self.triple_squoted_string(ctx)
            @α.option
            def _(ctx: Ctx) -> Any:
                self.squoted_string(ctx)

    @tatsu.rule
    def identifier(self, ctx: Ctx) -> Any:
        ctx.pattern(r'[A-Za-z]+[A-Za-z0-9_+-]*')

    @tatsu.rule
    def json_value(self, ctx: Ctx) -> Any:
        with ctx.choice() as α:
            @α.option
            def _(ctx: Ctx) -> Any:
                self.quoted_string(ctx)
            @α.option
            def _(ctx: Ctx) -> Any:
                self.json_obj(ctx)
            @α.option
            def _(ctx: Ctx) -> Any:
                self.json_array(ctx)

    @tatsu.rule
    def json_array(self, ctx: Ctx) -> Any:
        with ctx.choice() as α:
            @α.option
            def _(ctx: Ctx) -> Any:
                ctx.define(['first', 'rest', 'value'], [])
                ctx.token('[')
                with ctx.nameset('first'):
                    self.json_value(ctx)
                with ctx.nameset('rest'):
                    with ctx.loopopt() as cl:
                        cl.expecting(',')

                        @cl.exp
                        def _(ctx: Ctx) -> Any:
                            ctx.define(['value'], [])
                            ctx.token(',')
                            with ctx.nameset('value'):
                                self.json_value(ctx)
                ctx.token(']')
            @α.option
            def _(ctx: Ctx) -> Any:
                ctx.token('[')
                ctx.token(']')

    @tatsu.rule
    def json_name_value_pair(self, ctx: Ctx) -> Any:
        ctx.define(['name', 'value'], [])
        with ctx.nameset('name'):
            self.quoted_string(ctx)
        ctx.token(':')
        with ctx.nameset('value'):
            self.json_value(ctx)

    @tatsu.rule
    def json_obj(self, ctx: Ctx) -> Any:
        ctx.define(['first', 'rest'], [])
        ctx.token('{')
        with ctx.nameset('first'):
            self.json_name_value_pair(ctx)
        with ctx.nameset('rest'):
            with ctx.loopopt() as cl:
                cl.expecting(',')

                @cl.exp
                def _(ctx: Ctx) -> Any:
                    ctx.token(',')
                    self.json_name_value_pair(ctx)
        with ctx.optional():
            ctx.token(',')
        ctx.token('}')

    @tatsu.rule
    def query_variable(self, ctx: Ctx) -> Any:
        self.identifier(ctx)

    @tatsu.rule
    def query_name_value_pair(self, ctx: Ctx) -> Any:
        with ctx.choice() as α:
            @α.option
            def _(ctx: Ctx) -> Any:
                self.quoted_string(ctx)
                ctx.token(':')
                with ctx.group():
                    with ctx.choice() as β:
                        @β.option
                        def _(ctx: Ctx) -> Any:
                            self.json_value(ctx)
                        @β.option
                        def _(ctx: Ctx) -> Any:
                            self.query_variable(ctx)
            @α.option
            def _(ctx: Ctx) -> Any:
                self.quoted_string(ctx)
                ctx.token('~')
                self.quoted_string(ctx)

    @tatsu.rule
    def pattern_based_query_obj(self, ctx: Ctx) -> Any:
        ctx.token('{')
        self.query_name_value_pair(ctx)
        with ctx.loopopt() as cl:
            cl.expecting(',')

            @cl.exp
            def _(ctx: Ctx) -> Any:
                ctx.token(',')
                self.query_name_value_pair(ctx)
        ctx.token('}')

    @tatsu.rule
    def fileref_option(self, ctx: Ctx) -> Any:
        ctx.token('copy_to')

    @tatsu.rule
    def fileref_query_obj(self, ctx: Ctx) -> Any:
        ctx.define(['filename', 'options'], [])
        with ctx.group():
            with ctx.choice() as α:
                @α.option
                def _(ctx: Ctx) -> Any:
                    ctx.token('fileref')
                @α.option
                def _(ctx: Ctx) -> Any:
                    ctx.token('filename')
        ctx.token('(')
        with ctx.nameset('filename'):
            self.quoted_string(ctx)
        with ctx.nameset('options'):
            with ctx.loopopt() as cl:
                cl.expecting(',')

                @cl.exp
                def _(ctx: Ctx) -> Any:
                    ctx.token(',')
                    self.fileref_option(ctx)
                    ctx.token('=')
                    self.quoted_string(ctx)
        ctx.token(')')

    @tatsu.rule
    def query_obj(self, ctx: Ctx) -> Any:
        with ctx.choice() as α:
            @α.option
            def _(ctx: Ctx) -> Any:
                self.pattern_based_query_obj(ctx)
            @α.option
            def _(ctx: Ctx) -> Any:
                self.fileref_query_obj(ctx)

    @tatsu.rule
    def input_spec_each(self, ctx: Ctx) -> Any:
        self.identifier(ctx)
        ctx.token('=')
        self.query_obj(ctx)

    @tatsu.rule
    def input_spec_all(self, ctx: Ctx) -> Any:
        self.identifier(ctx)
        ctx.token('=')
        ctx.token('all')
        self.query_obj(ctx)

    @tatsu.rule
    def input_spec(self, ctx: Ctx) -> Any:
        with ctx.choice() as α:
            @α.option
            def _(ctx: Ctx) -> Any:
                self.input_spec_each(ctx)
            @α.option
            def _(ctx: Ctx) -> Any:
                self.input_spec_all(ctx)

    @tatsu.rule
    def input_specs(self, ctx: Ctx) -> Any:
        self.input_spec(ctx)
        with ctx.loopopt() as cl:
            cl.expecting(',')

            @cl.exp
            def _(ctx: Ctx) -> Any:
                ctx.token(',')
                self.input_spec(ctx)
        with ctx.optional():
            ctx.token(',')

    @tatsu.rule
    def output_specs(self, ctx: Ctx) -> Any:
        with ctx.choice() as α:
            @α.option
            def _(ctx: Ctx) -> Any:
                self.json_obj(ctx)
                with ctx.loopopt() as cl:
                    cl.expecting(',')

                    @cl.exp
                    def _(ctx: Ctx) -> Any:
                        ctx.token(',')
                        self.json_obj(ctx)
                with ctx.optional():
                    ctx.token(',')
            @α.option
            def _(ctx: Ctx) -> Any:
                ctx.token('none')

    @tatsu.rule
    def construct_cache_key_run(self, ctx: Ctx) -> Any:
        ctx.token('construct-cache-key-run')
        self.quoted_string(ctx)
        with ctx.optional():
            ctx.token('with')
            self.quoted_string(ctx)

    @tatsu.rule
    def run_statement(self, ctx: Ctx) -> Any:
        ctx.token('run')
        self.quoted_string(ctx)
        with ctx.optional():
            ctx.token('with')
            self.quoted_string(ctx)

    @tatsu.rule
    def file_list(self, ctx: Ctx) -> Any:
        self.quoted_string(ctx)
        with ctx.loopopt() as cl:
            cl.expecting(',')

            @cl.exp
            def _(ctx: Ctx) -> Any:
                ctx.token(',')
                self.quoted_string(ctx)

    @tatsu.rule
    def rule_parameters(self, ctx: Ctx) -> Any:
        with ctx.group():
            with ctx.choice() as α:
                @α.option
                def _(ctx: Ctx) -> Any:
                    ctx.token('inputs')
                    ctx.token(':')
                    self.input_specs(ctx)
                @α.option
                def _(ctx: Ctx) -> Any:
                    ctx.token('description')
                    ctx.token(':')
                    self.quoted_string(ctx)
                @α.option
                def _(ctx: Ctx) -> Any:
                    ctx.token('outputs')
                    ctx.token(':')
                    self.output_specs(ctx)
                @α.option
                def _(ctx: Ctx) -> Any:
                    ctx.token('executor')
                    ctx.token(':')
                    self.identifier(ctx)
                    self.json_obj(ctx)
                @α.option
                def _(ctx: Ctx) -> Any:
                    ctx.token('executor')
                    ctx.token(':')
                    self.identifier(ctx)
                @α.option
                def _(ctx: Ctx) -> Any:
                    ctx.token('watch-regex')
                    ctx.token(':')
                    self.quoted_string(ctx)
                @α.option
                def _(ctx: Ctx) -> Any:
                    ctx.token('publish')
                    ctx.token(':')
                    self.quoted_string(ctx)
                @α.option
                def _(ctx: Ctx) -> Any:
                    ctx.token('resources')
                    ctx.token(':')
                    self.json_obj(ctx)
                @α.option
                def _(ctx: Ctx) -> Any:
                    ctx.token('uses')
                    ctx.token(':')
                    self.file_list(ctx)

    @tatsu.rule
    def rule(self, ctx: Ctx) -> Any:
        ctx.define(['cachekeystmts', 'name', 'params', 'stmts'], [])
        ctx.token('rule')
        with ctx.nameset('name'):
            self.identifier(ctx)
        ctx.token(':')
        with ctx.nameset('params'):
            with ctx.loopopt() as cl:
                cl.expecting('<rule_parameters>')

                @cl.exp
                def _(ctx: Ctx) -> Any:
                    self.rule_parameters(ctx)
        with ctx.nameset('cachekeystmts'):
            with ctx.loopopt() as clb:
                clb.expecting('<construct_cache_key_run>')

                @clb.exp
                def _(ctx: Ctx) -> Any:
                    self.construct_cache_key_run(ctx)
        with ctx.nameset('stmts'):
            with ctx.loopopt() as clc:
                clc.expecting('<run_statement>')

                @clc.exp
                def _(ctx: Ctx) -> Any:
                    self.run_statement(ctx)

    @tatsu.rule
    def add_if_missing(self, ctx: Ctx) -> Any:
        with ctx.loopopt() as cl:
            cl.expecting('add-artifact', 'add-if-missing')

            @cl.exp
            def _(ctx: Ctx) -> Any:
                with ctx.choice() as α:
                    @α.option
                    def _(ctx: Ctx) -> Any:
                        ctx.token('add-if-missing')
                    @α.option
                    def _(ctx: Ctx) -> Any:
                        ctx.token('add-artifact')
        self.json_obj(ctx)

    @tatsu.rule
    def remember_executed_input(self, ctx: Ctx) -> Any:
        ctx.token('input')
        self.quoted_string(ctx)
        ctx.token(':')
        with ctx.loopopt() as cl:
            cl.expecting('<json_array>', '<json_obj>')

            @cl.exp
            def _(ctx: Ctx) -> Any:
                with ctx.choice() as α:
                    @α.option
                    def _(ctx: Ctx) -> Any:
                        self.json_obj(ctx)
                    @α.option
                    def _(ctx: Ctx) -> Any:
                        self.json_array(ctx)

    @tatsu.rule
    def remember_executed_output(self, ctx: Ctx) -> Any:
        ctx.token('output')
        ctx.token(':')
        self.json_obj(ctx)

    @tatsu.rule
    def remember_executed(self, ctx: Ctx) -> Any:
        ctx.token('remember-executed')
        ctx.token('transform')
        ctx.token(':')
        self.quoted_string(ctx)
        with ctx.loopopt() as cl:
            cl.expecting('<remember_executed_input>')

            @cl.exp
            def _(ctx: Ctx) -> Any:
                self.remember_executed_input(ctx)
        with ctx.loopopt() as clb:
            clb.expecting('<remember_executed_output>')

            @clb.exp
            def _(ctx: Ctx) -> Any:
                self.remember_executed_output(ctx)

    @tatsu.rule
    def exec_profile(self, ctx: Ctx) -> Any:
        ctx.token('executor-template')
        self.identifier(ctx)
        self.json_obj(ctx)

    @tatsu.rule
    def var_stmt(self, ctx: Ctx) -> Any:
        ctx.token('let')
        self.identifier(ctx)
        ctx.token('=')
        self.quoted_string(ctx)

    @tatsu.rule
    def include_stmt(self, ctx: Ctx) -> Any:
        ctx.token('include')
        self.quoted_string(ctx)

    @tatsu.rule
    def conditional_expr(self, ctx: Ctx) -> Any:
        self.quoted_string(ctx)

    @tatsu.rule
    def eval_statement(self, ctx: Ctx) -> Any:
        ctx.token('eval')
        self.quoted_string(ctx)

    @tatsu.rule
    def conditional(self, ctx: Ctx) -> Any:
        ctx.define(['condition', 'elif_clauses', 'else_clause', 'true_body'], [])
        ctx.token('if')
        with ctx.nameset('condition'):
            self.conditional_expr(ctx)
        ctx.token(':')
        with ctx.nameset('true_body'):
            self.declarations(ctx)
        with ctx.nameset('elif_clauses'):
            with ctx.loopopt() as cl:
                cl.expecting('elif')

                @cl.exp
                def _(ctx: Ctx) -> Any:
                    ctx.token('elif')
                    self.conditional_expr(ctx)
                    ctx.token(':')
                    self.declarations(ctx)
        with ctx.nameset('else_clause'):
            with ctx.optional():
                ctx.token('else')
                ctx.token(':')
                self.declarations(ctx)
        ctx.token('endif')

    @tatsu.rule
    def quotable_identifier(self, ctx: Ctx) -> Any:
        with ctx.choice() as α:
            @α.option
            def _(ctx: Ctx) -> Any:
                self.identifier(ctx)
            @α.option
            def _(ctx: Ctx) -> Any:
                self.quoted_string(ctx)

    @tatsu.rule
    def type_def_stmt(self, ctx: Ctx) -> Any:
        ctx.token('type')
        self.quotable_identifier(ctx)
        ctx.token(':')
        self.type_definition(ctx)

    @tatsu.rule
    def type_definition_component(self, ctx: Ctx) -> Any:
        with ctx.choice() as α:
            @α.option
            def _(ctx: Ctx) -> Any:
                ctx.token('description')
                ctx.token(':')
                self.quoted_string(ctx)
            @α.option
            def _(ctx: Ctx) -> Any:
                ctx.token('fields')
                ctx.token(':')
                self.identifier_list(ctx)

    @tatsu.rule
    def type_definition(self, ctx: Ctx) -> Any:
        self.type_definition_component(ctx)
        with ctx.loopopt() as cl:
            cl.expecting('<type_definition_component>')

            @cl.exp
            def _(ctx: Ctx) -> Any:
                self.type_definition_component(ctx)

    @tatsu.rule
    def identifier_list(self, ctx: Ctx) -> Any:
        self.quotable_identifier(ctx)
        with ctx.loopopt() as cl:
            cl.expecting(',')

            @cl.exp
            def _(ctx: Ctx) -> Any:
                ctx.token(',')
                self.quotable_identifier(ctx)

    @tatsu.rule
    def declarations(self, ctx: Ctx) -> Any:
        with ctx.loopplus() as cl:
            cl.expecting(
              'add-artifact',
              'add-if-missing',
              '<add_if_missing>',
              '<conditional>',
              'eval',
              '<eval_statement>',
              '<exec_profile>',
              'executor-template',
              'if',
              'include',
              '<include_stmt>',
              '<json_obj>',
              'let',
              'remember-executed',
              '<remember_executed>',
              'rule',
              'type',
              '<type_def_stmt>',
              '<var_stmt>',
              '{'
            )

            @cl.exp
            def _(ctx: Ctx) -> Any:
                with ctx.choice() as α:
                    @α.option
                    def _(ctx: Ctx) -> Any:
                        self.rule(ctx)
                    @α.option
                    def _(ctx: Ctx) -> Any:
                        self.include_stmt(ctx)
                    @α.option
                    def _(ctx: Ctx) -> Any:
                        self.var_stmt(ctx)
                    @α.option
                    def _(ctx: Ctx) -> Any:
                        self.add_if_missing(ctx)
                    @α.option
                    def _(ctx: Ctx) -> Any:
                        self.exec_profile(ctx)
                    @α.option
                    def _(ctx: Ctx) -> Any:
                        self.remember_executed(ctx)
                    @α.option
                    def _(ctx: Ctx) -> Any:
                        self.conditional(ctx)
                    @α.option
                    def _(ctx: Ctx) -> Any:
                        self.eval_statement(ctx)
                    @α.option
                    def _(ctx: Ctx) -> Any:
                        self.type_def_stmt(ctx)

    @tatsu.rule
    def all_declarations(self, ctx: Ctx) -> Any:
        with ctx.optional():
            self.declarations(ctx)
        ctx.eofcheck()


def main(filename, **kwargs):
    if not filename or filename == '-':
        import sys

        text = sys.stdin.read()
    else:
        import pathlib

        text = pathlib.Path(filename).read_text()

    parser = depfileParser()
    return parser.parse(text, filename=filename, **kwargs)


if __name__ == '__main__':
    import json
    from tatsu.util import asjson

    ast = generic_main(main, depfileParser, name='depfile')
    data = asjson(ast)
    print(json.dumps(data, indent=2))
