#!/usr/bin/env python
# -*- coding: utf-8 -*-

# CAVEAT UTILITOR
#
# This file was automatically generated by Grako.
#
#    https://pypi.python.org/pypi/grako/
#
# Any changes you make to it will be overwritten the next time
# the file is generated.


from __future__ import print_function, division, absolute_import, unicode_literals

from grako.parsing import graken, Parser

__version__ = (2016, 1, 29, 20, 20, 21, 4)

__all__ = [
    'grammarParser',
    'grammarSemantics',
    'main'
]


class grammarParser(Parser):
    def __init__(self,
                 whitespace=None,
                 nameguard=None,
                 comments_re=None,
                 eol_comments_re=None,
                 ignorecase=None,
                 left_recursion=True,
                 **kwargs):
        super(grammarParser, self).__init__(
            whitespace=whitespace,
            nameguard=nameguard,
            comments_re=comments_re,
            eol_comments_re=eol_comments_re,
            ignorecase=ignorecase,
            left_recursion=left_recursion,
            **kwargs
        )

    @graken()
    def _identifier_(self):
        self._pattern(r'[A-Za-z_]+[A-Za-z0-9_]*')

    @graken()
    def _var_list_(self):
        with self._choice():
            with self._option():
                self._identifier_()
            with self._option():
                self._identifier_()
                self._token(',')
                self._var_list_()
            self._error('no available options')

    @graken()
    def _quoted_string_(self):
        self._pattern(r'"[^"]*"')

    @graken()
    def _predicate_(self):
        with self._choice():
            with self._option():
                self._identifier_()
                self._token('.')
                self._identifier_()
                self._token('=')
                self._quoted_string_()
            with self._option():
                self._identifier_()
                self._token('.')
                self._identifier_()
                self._token('exists')
            with self._option():
                self._identifier_()
                self._token('.')
                self._identifier_()
                self._token('=')
                self._identifier_()
                self._token('.')
                self._identifier_()
            self._error('no available options')

    @graken()
    def _conj_predicate_(self):
        self._predicate_()

        def block0():
            self._token('and')
            self._predicate_()

        self._closure(block0)

    @graken()
    def _statement_(self):
        self._token('foreach')
        self._var_list_()
        with self._optional():
            self._token('where')
            self._conj_predicate_()
        with self._optional():
            self._token('withall')
            self._var_list_()
            with self._optional():
                self._token('where')
                self._conj_predicate_()
        self._token(';')


class grammarSemantics(object):
    def identifier(self, ast):
        return ast

    def var_list(self, ast):
        return ast

    def quoted_string(self, ast):
        return ast

    def predicate(self, ast):
        return ast

    def conj_predicate(self, ast):
        return ast

    def statement(self, ast):
        return ast


def main(filename, startrule, trace=False, whitespace=None, nameguard=None):
    import json
    with open(filename) as f:
        text = f.read()
    parser = grammarParser(parseinfo=False)
    ast = parser.parse(
        text,
        startrule,
        filename=filename,
        trace=trace,
        whitespace=whitespace,
        nameguard=nameguard)
    print('AST:')
    print(ast)
    print()
    print('JSON:')
    print(json.dumps(ast, indent=2))
    print()


if __name__ == '__main__':
    import argparse
    import string
    import sys


    class ListRules(argparse.Action):
        def __call__(self, parser, namespace, values, option_string):
            print('Rules:')
            for r in grammarParser.rule_list():
                print(r)
            print()
            sys.exit(0)


    parser = argparse.ArgumentParser(description="Simple parser for grammar.")
    parser.add_argument('-l', '--list', action=ListRules, nargs=0,
                        help="list all rules and exit")
    parser.add_argument('-n', '--no-nameguard', action='store_true',
                        dest='no_nameguard',
                        help="disable the 'nameguard' feature")
    parser.add_argument('-t', '--trace', action='store_true',
                        help="output trace information")
    parser.add_argument('-w', '--whitespace', type=str, default=string.whitespace,
                        help="whitespace specification")
    parser.add_argument('file', metavar="FILE", help="the input file to parse")
    parser.add_argument('startrule', metavar="STARTRULE",
                        help="the start rule for parsing")
    args = parser.parse_args()

    main(
        args.file,
        args.startrule,
        trace=args.trace,
        whitespace=args.whitespace,
        nameguard=not args.no_nameguard
    )
